services:
  socialite.api:
    container_name: socialite-api
    image: ilklmkn/socialite.api.web
    build:
      context: .
      dockerfile: Socialite.Api.Web/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - S3__AccessKey=minioadmin
      - S3__SecretKey=minioadmin
      - S3__Url=minioS3:9000
    depends_on:
      - db
      - minio
  
  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minioS3
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: socialite
  
  db:
    container_name: socialite-db
    image: postgres
    environment:
      - POSTGRES_DB=Socialite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=redispassword
      - REDIS_USER=redisuser
      - REDIS_USER_PASSWORD=redisuserpassword
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redisdata:/data

volumes:
  postgres-data:
  minio_data: